.github/workflows/integration-test-images.yml, install-m2-from-mirror/dist/index.js, install-m2-from-mirror/index.js, magento-integration-tests/7.2/action.yml, magento-integration-tests/7.3/action.yml, magento-integration-tests/7.4/action.yml, magento-integration-tests/Dockerfile:7.2, magento-integration-tests/Dockerfile:7.3, magento-integration-tests/Dockerfile:7.4, magento-integration-tests/README.md, magento-integration-tests/action.yml, magento-integration-tests/entrypoint.sh
@jissereitsma I have made some further changes to the integration tests, mostly triggered by myself not being able to run them on Magento 2.4.0.
Notable changes:
- main invocation is now via a github action (which in turn uses the docker image) rather than straight to using docker. 
- images are now built automatically and pushed to https://hub.docker.com/r/extdn/magento-integration-tests-action/tags via  https://github.com/extdn/github-actions-m2/compare/integration-tests?expand=1#diff-c2141bf18100b64b63345d9e0d819f2c
- To make usage easier I have also switched to using the authentication less mirror of repo.magento.com that I set up
- Updated the elasticsearch config (taken from the warden project) that worked in my testing
Note to self - this …
=> Integration tests

magento-integration-tests/docker-files/phpunit.xml, magento-quick-integration-tests/docker-files/phpunit.xml
Magento 2.4.3 added a new config option `TESTS_POST_INSTALL_SETUP_COMMAND_CONFIG_FILE` for integration tests. Not having it leads to an error during the test execution, see e.g. https://github.com/firegento/firegento-magesetup2/pull/200/checks?check_run_id=3372015558. I did not test it, but I think this new config option should just be ignored by older versions, so this change should be backwards-compatible.
=> Add new 2.4.3 config option

magento-integration-tests/docker-files/phpunit.xml
It is a common practice to move all source code into a `src` directory. Hence, we should also read integration test files from there.
=> Support modules with src directory

README.md
I've added the examples from the readme to our project and the actions were executed twice for PRs: One time for the push, one time for the branch. This PR updates the docs to make them run by default on either the master branch or a PR but not both.
=> docs: prevent Action running twice for PRs from a branch in the repo

.github/workflows/coding-standard-images.yml
Since the addition of php 7.4 to the magento coding standard action the [build of the images]( https://github.com/extdn/github-actions-m2/actions/runs/1330938064) fails with the error:
```
unable to prepare context: path "magento-coding-standard-tests/." not found
```
this should fix #43
=> fix coding standard image build

magento-integration-tests/7.0/action.yml, magento-integration-tests/7.1/action.yml, magento-integration-tests/7.2/action.yml, magento-integration-tests/7.3/action.yml, magento-integration-tests/7.4/action.yml, magento-integration-tests/entrypoint.sh
The goal of this PR is to make possible to execute integration tests with this action for projects with magento enterprise edition.
By adding a new action parameter called project_name (default value: `magento/project-community-edition`), we allow the user to setup a different project to install if necessary, like magento/project-enterprise-edition
=> adding project option to integration-tests action

magento-integration-tests/7.4/action.yml, magento-integration-tests/Dockerfile:7.0, magento-integration-tests/Dockerfile:7.1, magento-integration-tests/Dockerfile:7.2, magento-integration-tests/Dockerfile:7.3, magento-integration-tests/Dockerfile:7.4, magento-integration-tests/entrypoint.sh
This PR provides a way to configure the composer version used in integration tests.
Composer 2 was only installed in the Dockerfile for 7.4 so I added the config option only there. IIRC composer 2 requires 7.4? (or at least 7.3?)
=> feat: allow configuration of composer version in integration tests

php-compatibility/7.3/action.yml, php-compatibility/7.4/action.yml, php-compatibility/Dockerfile:7.3, php-compatibility/Dockerfile:7.4, php-compatibility/action.yml, php-compatibility/entrypoint.sh, php-compatibility/problem-matcher.json
Apologies I'm on a windows machine at the moment so can't fully test this e.g can't even clone repo due to file naming convention. And can only do so much using WSL.
So basically I've taken a wild stab in the dark on how I think this should work. Could need further work. Also what that means is that I can't do a great deal of editing if changes are required to the PR.
Personally for me I think it would be really handy to have a static code analysis with the specifically the PHPCompatibility coding standard but allowing adjustment of test version.
=> static code analysis with the PHPCompatibility Coding Standard

magento-integration-tests/Dockerfile:7.0, magento-integration-tests/Dockerfile:7.1, magento-integration-tests/Dockerfile:7.2, magento-integration-tests/Dockerfile:7.3, magento-integration-tests/Dockerfile:7.4, magento-integration-tests/Dockerfile:8.1
The PHP extension 'pcntl' is [recommended by Magento](https://github.com/magento/magento2/blob/83f3d01e1a4fe6ac7b79c9996403a32643c3b399/composer.json#L101-L103), but is missing from these images. A module I'm working on [uses this extension](https://github.com/Ethan3600/magento2-CronjobManager/blob/1057e3406bbf927a23341afb6bfef176a878a87f/composer.json#L9-L11) in [its tests](https://github.com/Ethan3600/magento2-CronjobManager/blob/1057e3406bbf927a23341afb6bfef176a878a87f/Test/Integration/ProcessKillRequestsTest.php#L139).
This pull request adds the 'pcntl' extension to all integration test images.
=> Add pcntl extension, as suggested by Magento

magento-integration-tests/docker-files/install-config-mysql-with-es.php, magento-integration-tests/entrypoint.sh
By default, Magento 2.4.6 uses OpenSearch, leading to all integration tests' failure. 
To resolve this issue, it is recommended to include a tag during installation that sets the search engine to ES7. If you want to replicate the problem, simply create an integration test for Magento 2.4.6 using PHP 8.1 and commit it to GitHub. This will show that the integration test has indeed failed.
=> Integration tests fail for magento 2.4.6 as it uses Opensearch by default 

magento-quick-integration-tests/entrypoint.sh
To avoid quick integration test failures in Magento 2.4.6, it's advisable to set the search engine to ES7 by including a tag during installation. OpenSearch, the default search engine in Magento 2.4.6, can cause this issue. If you wish to replicate the problem, create an integration test for Magento 2.4.6 using PHP 8.1 and commit it to GitHub. This will verify the failed quick integration test.
=> Quick Integration tests fail for magento 2.4.6 as it uses Opensearch by default

.github/workflows/coding-standard-images.yml, .github/workflows/integration-test-images.yml, .github/workflows/php-compatibility.yml, .github/workflows/phpstan-images.yml, .github/workflows/unit-test-images.yml
We should only update Docker Images when we actually push to `master`. Otherwise, any PR changes our Docker images, which is quite bad :see_no_evil:
=> Only build images on master push

magento-phpstan/entrypoint.sh
PHPStan has - only in certain cases, but still - issues with symlinks. See e.g.:
https://github.com/phpstan/phpstan/issues/7241
https://github.com/phpstan/phpstan/issues/6585
This PR suggests to use [`COMPOSER_MIRROR_PATH_REPOS`](https://getcomposer.org/doc/03-cli.md#composer-mirror-path-repos) for the PHPStan action, so that the package is actually copied and not symlinked from the local path repository to fix such issues.
=> Do not use symlinks with PHPStan

README.md, install-m2-from-mirror/action.yml, install-m2-from-mirror/dist/index.js, install-m2-from-mirror/index.js, magento-integration-tests/7.0/action.yml, magento-integration-tests/7.1/action.yml, magento-integration-tests/7.2/action.yml, magento-integration-tests/7.3/action.yml, magento-integration-tests/7.4/action.yml, magento-integration-tests/8.1/action.yml, magento-integration-tests/8.2/action.yml, magento-integration-tests/README.md, magento-integration-tests/entrypoint.sh, magento-performance-compare/action.yml, magento-phpstan/entrypoint.sh, magento-quick-integration-tests/README.md, magento-quick-integration-tests/action.yml, magento-quick-integration-tests/entrypoint.sh, magento-unit-tests/7.3/action.yml, magento-unit-tests/7.4/action.yml, magento-unit-tests/8.1/action.yml, magento-unit-tests/8.2/action.yml, magento-unit-tests/entrypoint.sh
While reviewing #101, I noticed that the way that GitHub Actions "inputs" were handled was not consistent across all Actions in this repository. This pull request aims to make them consistent.
Changes include:
- Rename `ce_version` and `ce-version` inputs to `magento_version` (maintaining backwards-compatibility)
- Allow specifying `project_name` where `magento/project-community-edition` was hard-coded. Note that not all instances of this are fixed here.
- Unset extra environment variables in `action.yml` files for inputs
- Handle input variables in `entrypoint.sh` scripts as intended
- Remove unused inputs: `extension-name`, `extension-package-name`
Changes are best viewed with "ignore white-space" as my editor has removed trailing white-space in several files. If you would prefer these …
=> Make GitHub Actions inputs consistent

magento-phpstan/entrypoint.sh
While working on a Magento module with the PHPStan GitHub Action from this repository, I am getting some unexpected errors like "return statement is missing" when it isn't missing. I've done a little testing locally and when I inspect the same files within the Magento root, these extra errors don't show up. I have tested that (when I introduce an intentional issue) PHPStan still reports other issues with this set-up.
Here's an example run with invalid results https://github.com/Ethan3600/magento2-CronjobManager/actions/runs/8394567803/job/22992004531?pr=206
=> Check files within Magento project root

.github/workflows/docker.yml, .github/workflows/integration-test-images.yml, .github/workflows/php-compatibility.yml, .github/workflows/phpstan-images.yml, .github/workflows/unit-test-images.yml
We already rebuild the coding standard image weekly. Let's also rebuild other images weekly. This allows us to better detect when upstream breaks something that we need to adjust our images in order to accommodate.
=> Rebuild all images weekly

.github/workflows/phpstan-images.yml
The automated build for the PHPStan image failed because it depends on the integration test image, which didn't exist at the time. Moments later, it did exist, so this build will work next time it runs.
This change allows the build to work properly, and also rebuilds these images when the upstream/parent image gets any changes - like adding a PHP extension.
=> Build PHPStan image after its parent completes

magento-integration-tests/entrypoint.sh, magento-quick-integration-tests/entrypoint.sh
Here's my best guess at fixing the 2.4.8 integration tests.
In 2.4.8 there is no longer an `elasticsearch7` option
https://github.com/magento/magento2/blob/eb491c0533c106ca44ee219c545c617f53aea2bc/setup/src/Magento/Setup/Model/SearchConfigOptionsList.php#L149-L155
I have generated a failing test example on [this repo](https://github.com/convenient/magento-github-actions-test) and the failure can be seen in [this run](https://github.com/convenient/magento-github-actions-test/actions/runs/14704692563/job/41262032689).
It fails to install with 
```
[Progress: 735 / 1477]
Installing search configuration...
In SearchConfig.php line 97:
Search engine 'elasticsearch7' is not an available search engine.  
```
Additionally, i think this file is baked into the docker image. Any tips for how I can …
=> Fix 2.4.8 integration tests

magento-phpstan/Dockerfile, magento-phpstan/Dockerfile:7.3, magento-phpstan/Dockerfile:7.4, magento-phpstan/Dockerfile:8.1, magento-phpstan/Dockerfile:8.2, magento-phpstan/Dockerfile:8.3, magento-phpstan/Dockerfile:8.4
This is a follow-up to a4b11d149919c38a226409b1d4d667526f37d57b (merged as #124) where we dropped support for Composer v1 and renamed Composer v2 to just 'composer'.
Thanks to @sprankhub for highlighting this bug to me.
=> Correct command name for composer

magento-integration-tests/docker-files/install-config-mysql-with-es.php, magento-integration-tests/entrypoint.sh
This is a follow-up to #123 where we added the ability to use elasticsearch8 instead of elasticsearch7 on Magento 2.4.8. I'm getting errors about this configuration downstream.
Example action failure: https://github.com/Ethan3600/magento2-CronjobManager/actions/runs/14779752203/job/41495908405
=> Use configured version of elasticsearch

magento-integration-tests/docker-files/phpunitv10.xml, magento-integration-tests/entrypoint.sh
Details of what I have encountered can be seen here https://github.com/magento/magento2/issues/39907
But in short, annotations are not working in 2.4.8 because of the changes to the phpunit event subscription system.
```php
/**
* @magentoAdminConfigFixture some/config/value 1
*/
```
After speaking with @michielgerritsen he [suggests](https://github.com/michielgerritsen/magento2-extension-integration-test/commit/c15ada83f77fb7cceb421f6a4395a52c3292bad9) its because we're using an old phpunit.xml, and basing off a fresh M2 installation could be the way to go.
I've had a look at the code and it seems like we're pulling in the phpunit 9 series XML, and trying to run it against the phpunit 10 series code, which has different event system handling.
I do not know how to test this fully, without …
=> Attempt to use phpunit 10 compatible event system

magento-unit-tests/docker-files/phpunitv10.xml, magento-unit-tests/entrypoint.sh
Just as @convenient found issues when [trying to ran Integration tests](https://github.com/extdn/github-actions-m2/pull/129) on PHP Unit v10, I saw the same exact issue on Unit Testing. For my case the only thing I was able to test was the PHP Unit XML and it works for me.
Error:
```
There was 1 PHPUnit test runner warning:
1) Test results may not be as expected because the XML configuration file did not pass validation:
Line 8:
- Element 'filter': This element is not expected.
```
I'm glad to contribute, and I'd like to say thanks for all of your work for this community.
=> Attempt to use phpunit 10 compatible event system for PHP Unit testing
